### ISSUE TITLE
Create Dropbox paper for new user

### ISSUE THREAD

**Issue by AdityaHirapara** [wdlsvnit/paper-extension#10]
**Note:** You can use direct authtoken for debugging, Dropbox provides this service. You don't need authorisation.

**Comment by Dhruvi16** [comment]
I ll do this.

**Comment by Dhruvi16** [comment]
where will i create it?

**Comment by ajayns** [comment]
What do you mean where? Can you please elaborate? @Dhruvi16

**Comment by Dhruvi16** [comment]
I got the thing.
