### ISSUE TITLE
Disable "save to paper" option when user is not authenticated

### ISSUE THREAD

**Issue by AdityaHirapara** [wdlsvnit/paper-extension#14]
If auth token is not granted to app, we can't save text to paper, so disable context menu option until app is authorised, and enable it when token is received by app.

**Comment by Insiyaa** [comment]
I'll do this

**Comment by AdityaHirapara** [comment]
Go ahead!

**Comment by Insiyaa** [comment]
Is this intended? Also the context menu is removed...
![](https://user-images.githubusercontent.com/29259374/40967168-02588eee-68d0-11e8-9bef-295a568e852b.png)

**Comment by AdityaHirapara** [comment]
Yeah! looks nice!
